/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HospitalManagementSystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Software Engineers
 */
 class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        addNewPatientRecordButton = new javax.swing.JButton();
        addDiagnosisButton = new javax.swing.JButton();
        patientHistoryButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();
        updateRecordButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 1000));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(0, 204, 204));
        headerLabel.setText("Welcome to Hospital Management System");
        getContentPane().add(headerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 0, 1006, -1));

        addNewPatientRecordButton.setBackground(new java.awt.Color(0, 204, 153));
        addNewPatientRecordButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addNewPatientRecordButton.setForeground(new java.awt.Color(255, 51, 255));
        addNewPatientRecordButton.setText("Add New Record");
        addNewPatientRecordButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(204, 204, 0), new java.awt.Color(0, 0, 204), new java.awt.Color(153, 0, 153)));
        addNewPatientRecordButton.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalManagementSystem/addPatientRecordIcon.png"))); // NOI18N
        addNewPatientRecordButton.setIconTextGap(2);
        addNewPatientRecordButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalManagementSystem/addPatientRecordIcon.png"))); // NOI18N
        addNewPatientRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewPatientRecordButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addNewPatientRecordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 300, 100));

        addDiagnosisButton.setBackground(new java.awt.Color(255, 153, 153));
        addDiagnosisButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addDiagnosisButton.setForeground(new java.awt.Color(204, 0, 204));
        addDiagnosisButton.setText("Add Diagnosis Information");
        addDiagnosisButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 204)));
        addDiagnosisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDiagnosisButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addDiagnosisButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, 310, 100));

        patientHistoryButton.setBackground(new java.awt.Color(204, 204, 255));
        patientHistoryButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        patientHistoryButton.setForeground(new java.awt.Color(204, 0, 204));
        patientHistoryButton.setText("Full History of Patient");
        patientHistoryButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 204)));
        patientHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientHistoryButtonActionPerformed(evt);
            }
        });
        getContentPane().add(patientHistoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 100, 300, 100));

        logoutButton.setBackground(new java.awt.Color(51, 0, 0));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 0, 255));
        logoutButton.setText("Logout");
        logoutButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 204)));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 270, 250, 100));

        aboutButton.setBackground(new java.awt.Color(255, 255, 204));
        aboutButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        aboutButton.setForeground(new java.awt.Color(204, 0, 204));
        aboutButton.setText("About The Hospital");
        aboutButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 204)));
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(aboutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 270, 250, 100));

        updateRecordButton.setBackground(new java.awt.Color(153, 153, 0));
        updateRecordButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updateRecordButton.setForeground(new java.awt.Color(204, 0, 204));
        updateRecordButton.setText("Update Patient Record");
        updateRecordButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 204)));
        updateRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRecordButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateRecordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 300, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalManagementSystem/loginBG (2).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-860, -830, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientHistoryButtonActionPerformed
        setVisible(false);    
        new FullPatientHistory().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_patientHistoryButtonActionPerformed

    private void addNewPatientRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewPatientRecordButtonActionPerformed
        setVisible(false);     
        new AddNewPatient().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_addNewPatientRecordButtonActionPerformed

    private void addDiagnosisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDiagnosisButtonActionPerformed
       setVisible(false);     
        new AddDiagnosisInfo().setVisible(true);// TODO add your handling code here: // TODO add your handling code here:
    }//GEN-LAST:event_addDiagnosisButtonActionPerformed

    private void updateRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRecordButtonActionPerformed
     setVisible(false);     
        new UpdatePatientRecord().setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_updateRecordButtonActionPerformed

    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        setVisible(false);       
        new AboutHospital().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_aboutButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
int select=JOptionPane.showConfirmDialog(this,"Do you want logout from Home", "select",JOptionPane.YES_NO_OPTION) ;  
  if(select==0){
      setVisible(false);
      new Login().setVisible(true);
  }        // TODO add y        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JButton addDiagnosisButton;
    private javax.swing.JButton addNewPatientRecordButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton patientHistoryButton;
    private javax.swing.JButton updateRecordButton;
    // End of variables declaration//GEN-END:variables
}
